### ISSUE TITLE
Portfolio Nav

### ISSUE THREAD

**Issue by InikonZS** [scientist26/singolo#2]
Пункт меню в блоке портфолио подсвечивается, но изображения почему-то не меняются. По коду смотрю, функция перемешивания на месте. Детально не анализировал. Mozilla.
В Хроме работает. Зачтено, извиняюсь.

**Comment by scientist26** [comment]
Действительно, не работает..
Зато в хроме все ок)

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Без
вирусов. www.avast.ru
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

вт, 31 мар. 2020 г. в 21:29, InikonZS <notifications@github.com>:
